Repository mudit023/templates, pull requests merged in 2022-10, with the labels that each got.

#85 some login page templates added
  Login Page/Images/google-svgrepo-com.svg
  Login Page/Images/login1.svg
  Login Page/Login1.html
  Login Page/Login2.html
  Login Page/README.md
Labels: hacktoberfest-accepted

#79 Animated login form changes
  Amazing Animated Login Form/README.md
  Amazing Animated Login Form/app.js
  Amazing Animated Login Form/index.html
  Amazing Animated Login Form/signup.css
Labels: documentation, hacktoberfest-accepted

#81 Added Profile Card
  Profile-card-6/README.md
  Profile-card-6/Screenshot1.png
  Profile-card-6/index.html
  Profile-card-6/style.css
Labels: fix, hacktoberfest-accepted, hacktoberfest

#89 Animated newsletter changes
  animated-newsletter/index.html
  animated-newsletter/script.js
  animated-newsletter/style.css
Labels: fix, hacktoberfest-accepted, hacktoberfest

#90 Added MCQ-Quiz-App as a template
  MCQ-Quiz-App/README.md
  MCQ-Quiz-App/index.html
  MCQ-Quiz-App/script.js
  MCQ-Quiz-App/style.css
Labels: fix, hacktoberfest-accepted, hacktoberfest

#98 Changed Readme File
  Drag and Drop/Demo.gif
  Drag and Drop/README.md
Labels: documentation, good first issue, hacktoberfest-accepted, hacktoberfest

#99 Added Image-Carousel
  Image-Carousel/Demo/demo of image-carousel.gif
  Image-Carousel/Readme.md
  Image-Carousel/Screenshot1.png
  Image-Carousel/Screenshot2.png
  Image-Carousel/dog.jpg
  Image-Carousel/index.html
  Image-Carousel/p1.jpg
  Image-Carousel/p2.jpg
  Image-Carousel/p3.jpg
  Image-Carousel/script.js
  Image-Carousel/style.css
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest, needChanges

#104 Added smooth Navigation bar template
  Navigation Bar Template/Images/681086_17136101_3096767_2dbcc4ed_image.png
  Navigation Bar Template/Images/Screenshot (9).png
  Navigation Bar Template/Readme.md
  Navigation Bar Template/index.html
  Navigation Bar Template/style.css
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#107 Navbar mobile changes
  navbar-mobile/index.html
  navbar-mobile/script.js
  navbar-mobile/style.css
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#113 Quiz app changes
  Quiz-App/README.md
  Quiz-App/gif-quiz-app.gif
  Quiz-App/index.html
  Quiz-App/question-interface.png
  Quiz-App/result.png
  Quiz-App/script.js
  Quiz-App/style.css
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#118 Animated-profile-card
  Profile-Card-8/Readme.md
  Profile-Card-8/action.js
  Profile-Card-8/images/Profile-Card.gif
  Profile-Card-8/images/Screenshot.jpg
  Profile-Card-8/images/profile-pic.jpg
  Profile-Card-8/index.html
  Profile-Card-8/style.css
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#121 Update Readme.md
  Profile-Card-8/Readme.md
Labels: documentation, enhancement, hacktoberfest-accepted, hacktoberfest

#125 profile card
  Animated profile card/img/email.png
  Animated profile card/img/github.png
  Animated profile card/img/hero.png
  Animated profile card/img/instagram.png
  Animated profile card/img/screenshot-active.png
  Animated profile card/img/screenshot.png
  Animated profile card/img/twitter.png
  Animated profile card/index.html
  Animated profile card/readme.md
  Animated profile card/style.css
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#127 Main
  Animated profile card/img/screenshot-active.png
  Animated profile card/img/screenshot.gif
  Animated profile card/img/screenshot.png
  Animated profile card/index.html
  Animated profile card/readme.md
Labels: fix

#123 Slider Profile Cards
  Slider Profile Card/Readme.md
  Slider Profile Card/img.jpg
  Slider Profile Card/index.html
  Slider Profile Card/jquery.js
  Slider Profile Card/owl.carousel.min.css
  Slider Profile Card/owl.carousel.min.js
  Slider Profile Card/script.js
  Slider Profile Card/styles.css
Labels: enhancement, Discussion, hacktoberfest-accepted, hacktoberfest, needChanges
